on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@main
        id: ghrelease
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: rd-api
          default-branch: main
